Pre-checks in the workflow

diff --git a/.github/workflows/publish-pypi.yml b/.github/workflows/publish-pypi.yml
--- a/.github/workflows/publish-pypi.yml
+++ b/.github/workflows/publish-pypi.yml
@@ -16,7 +16,7 @@ env:
 
 jobs:
   details:
-    name: Extract Tag Details
+    name: Extract Tag Details and Pre-checks
     runs-on: ubuntu-latest
     environment: release-with-approval
     outputs:
@@ -35,6 +35,38 @@ jobs:
           echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
           echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
           echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
+
+      - name: Check if GitHub Release Exists
+        id: check_release
+        run: |
+          if gh release view ${{ steps.extract_tag.outputs.tag_name }} > /dev/null 2>&1; then
+            echo "skip=true" >> "$GITHUB_ENV"
+            exit 1
+          else
+            echo "skip=false" >> "$GITHUB_ENV"
+          fi
+
+      - name: Fetch PyPI Version
+        id: check_pypi
+        run: |
+          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
+          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
+          if [ -z "$latest_previous_version" ]; then
+            echo "Package not found on PyPI."
+            latest_previous_version="0.0.0"
+          fi
+          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
+
+      - name: Compare Versions
+        run: |
+          NEW_VERSION=${{ steps.extract_tag.outputs.new_version }}
+          LATEST_VERSION=$latest_previous_version
+          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
+            echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
+            exit 1
+          else
+            echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
+          fi
 
   test_backward_compatibility:
     name: Test Backward Compatibility
@@ -59,36 +91,9 @@ jobs:
       - name: Run Tox Tests
         run: tox
 
-  check_pypi:
-    name: Check PyPI
-    needs: [details, test_backward_compatibility]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fetch PyPI Version
-        run: |
-          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
-          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
-          if [ -z "$latest_previous_version" ]; then
-            echo "Package not found on PyPI."
-            latest_previous_version="0.0.0"
-          fi
-          echo "Latest version on PyPI: $latest_previous_version"
-          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
-
-      - name: Compare Versions
-        run: |
-          NEW_VERSION=${{ needs.details.outputs.new_version }}
-          LATEST_VERSION=$latest_previous_version
-          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
-            echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
-            exit 1
-          else
-            echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
-          fi
-
   setup_and_build:
     name: Setup and Build
-    needs: [details, check_pypi]
+    needs: [details, test_backward_compatibility]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -138,7 +143,7 @@ jobs:
 
   github_release:
     name: Create GitHub Release
-    needs: [setup_and_build]
+    needs: [details, setup_and_build]
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -152,16 +157,6 @@ jobs:
           name: dist
           path: dist/
 
-      - name: Check if Release Exists
-        id: check_release
-        run: |
-          if gh release view ${{ needs.details.outputs.tag_name }} > /dev/null 2>&1; then
-            echo "skip=true" >> $GITHUB_ENV
-          else
-            echo "skip=false" >> $GITHUB_ENV
-          fi
-
       - name: Create GitHub Release
-        if: env.skip == 'false'
         run: |
           gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
